module.exports = [
  [
      'not a holiday',
      'not a holiday',
      'the first day of Compitalia. Originally a moveable feast which would be celebrated on a date determined by the presiding authorities, it was fixed to January 3rd to 5th in the early Empire. A hen would be sacrificed at the crossroads on a temporary altar, signalling the beginning of three days of celebration. In the countryside, landowners would build small altars at the boundary shared with neighbors. They would leave a plough and a small doll for each family member.',
      'the second day of Compitalia. Originally a moveable feast which would be celebrated on a date determined by the presiding authorities, it was fixed to January 3rd to 5th in the early Empire. A hen would be sacrificed at the crossroads on a temporary altar, signalling the beginning of three days of celebration. In the countryside, landowners would build small altars at the boundary shared with neighbors. They would leave a plough and a small doll for each family member.',
      'the third and last day of Compitalia. Originally a moveable feast which would be celebrated on a date determined by the presiding authorities, it was fixed to January 3rd to 5th in the early Empire. A hen would be sacrificed at the crossroads on a temporary altar, signalling the beginning of three days of celebration. In the countryside, landowners would build small altars at the boundary shared with neighbors. They would leave a plough and a small doll for each family member.',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'Agonalia, a festival in honor of Janus, the two-faced god. Janus was the god of doorways and thresholds, and gives us the name of the month January. There are many myths as to his origins, one naming him as the son of Apollo and the first king of Latium. Another says that Janus welcomed Saturn to earth after Saturn was driven out of heaven by Jupiter. Doorways were considered weakpoints - both in war and in the spirit world. This festival was originally for the protection of the king, and involved the sacrifice of a ram - hence the name, from "agnus."',
      'not a holiday',
      'the first day of Carmentalia, a five-day festival to Carmentis or Carmenta, the mother of Evander and a prophetess. She eventually became the goddess of childbirth.',
      'the second day of Carmentalia, a five-day festival to Carmentis or Carmenta, the mother of Evander and a prophetess. She eventually became the goddess of childbirth.',
      'the third day of Carmentalia, a five-day festival to Carmentis or Carmenta, the mother of Evander and a prophetess. She eventually became the goddess of childbirth. Also, the Ides of January, a festival to Jupiter.',
      'the fourth day of Carmentalia, a five-day festival to Carmentis or Carmenta, the mother of Evander and a prophetess. She eventually became the goddess of childbirth.',
      'the fifth and last day of Carmentalia, a five-day festival to Carmentis or Carmenta, the mother of Evander and a prophetess. She eventually became the goddess of childbirth.',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday'
  ],
  [ 'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'the first day of Parentalia. During the Dies Parentales, the Romans would commemorate the dead, especially their parents, and drink heavily. Offerings of milk, alcohol and food would be left on graves to satisfy the hunger of the dead and keep them from seeking out the living. Also, the Ides of February.',
    'the second day of Parentalia. During the Dies Parentales, the Romans would commemorate the dead, especially their parents, and drink heavily. Offerings of milk, alcohol and food would be left on graves to satisfy the hunger of the dead and keep them from seeking out the living. ',
    'Lupercalia - a festival to Lupercus or Faunus. The festival would begin at the wolf den where Romulus and Remus were raised according to legend. Youths in two teams would dress in blood and goat hides and participate in foot races, swatting bystanders with leather straps or "februa" - that which purifies. Women hoping to conceive a male heir would try to get hit with the strap. This was replaced with Valentine\'s Day by Christians. Also the third day of Parentalia. During the Dies Parentales, the Romans would commemorate the dead, especially their parents, and drink heavily. Offerings of milk, alcohol and food would be left on graves to satisfy the hunger of the dead and keep them from seeking out the living. ',
    'the fourth day of Parentalia. During the Dies Parentales, the Romans would commemorate the dead, especially their parents, and drink heavily. Offerings of milk, alcohol and food would be left on graves to satisfy the hunger of the dead and keep them from seeking out the living. ',
    'Quirinalia, a holiday devoted to Quirinus, originally a Sabine war god, but adopted by the Romans as the deified Romulus. Also the fifth day of Parentalia. During the Dies Parentales, the Romans would commemorate the dead, especially their parents, and drink heavily. Offerings of milk, alcohol and food would be left on graves to satisfy the hunger of the dead and keep them from seeking out the living. ',
    'the sixth day of Parentalia. During the Dies Parentales, the Romans would commemorate the dead, especially their parents, and drink heavily. Offerings of milk, alcohol and food would be left on graves to satisfy the hunger of the dead and keep them from seeking out the living. ',
    'the seventh day of Parentalia. During the Dies Parentales, the Romans would commemorate the dead, especially their parents, and drink heavily. Offerings of milk, alcohol and food would be left on graves to satisfy the hunger of the dead and keep them from seeking out the living. ',
    'the eighth and last day of Parentalia. During the Dies Parentales, the Romans would commemorate the dead, especially their parents, and drink heavily. Offerings of milk, alcohol and food would be left on graves to satisfy the hunger of the dead and keep them from seeking out the living. ',
    'Feralia - a holiday to the gods of the netherworld and the souls of the deceased, in particular dead ancestors. Romans brought offerings to their tombs including wreaths and bread soaked in wine. There they sprinkled grain, salt, and violet petals. When once the Romans ignored the festival because of preoccupation with war, it was said that the dead ancestors roamed the streets as angry ghosts. To mark the mournings, marriages were prohibited on this day, magistrates did not wear their insignia and all temples were closed for business. According to the writer Ovid, on this day an old drunken woman would sit in a circle with other girls performing rites in the name of the Mute Goddess, Tacita. The woman would place three bits of incense, with three of her fingers, beneath a threshold where a mouse is unknowingly buried. She then rolled seven black beans in her mouth and smeared the head of a fish with pitch, impaling it with a bronze needle, and roasting it in a fire. After that she formally declaimed the purpose of her actions, saying "I have gagged spiteful tongues and muzzled unfriendly mouths" (in Latin "Hostiles linguas inimicaque uinximus ora" and then departed intoxicated.Also the ninth and final day of Parentalia. During the Dies Parentales, the Romans would commemorate the dead, especially their parents, and drink heavily. Offerings of milk, alcohol and food would be left on graves to satisfy the hunger of the dead and keep them from seeking out the living. ',
    'not a holiday',
    'Terminalia, a holiday devoted to Terminus, possibly another name for Jupiter. It was a festival to the god of boundaries and probably originated in the country where farmers would meet their neighbors at the borders to their lands, agree on them and leave small sacrifices that their lands would not be invaded by any form of evil.',
    'Regifugium, another holiday devoted To Terminus. Later Romans thought it commemorated the expulsion of Rome\'s last king, but like most of the festivals, it probably had its origin well before that.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday'
  ],
  ['Kalends of March - the original beginning of the new year. This was the day for rekindling the eternal flame tended by the Vestals, which represented the life of Rome. The city would be hung with fresh laurels, and the Salii (leaping priests) would dance in honor of Mars, patron of the month, for nineteen days. The dancers would carry sacred shields and dine at a different house every night. This was also the time when soldiers were called up for the year\'s campaigns.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'Equirria - a race for two-horse chariots to support the army and boost public moral. Priests would sanctify the army and a scapegoat was driven out of the city.',
    'not a holiday',
    'not a holiday',
    'Liberalia - a festival in honor of Liber and Libera, celebrating freedom from evil, burdens, care and folly. Also a holiday on which young boys would declare their adulthood on the occurrence closest to their sixteenth birthday.',
    'not a holiday',
    'Quinquatrus - a festival to Mars and Minerva, devoted to learning. Chiefly celebrated by students and teachers, it was also important to doctors and artisans.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'Tubilustrium, a festival of cleaning the trumpets to insure a successful year of campaigns. A female lamb was sacrificed in the Hall of the Shoemakers and the twelve youths of the Salii (the leaping priests) danced through the streets.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday'
  ],
  ['not a holiday',
    'not a holiday',
    'not a holiday',
    'the first day of the Ludi Megalenses. Originally celebrated on March 27 when the statue of the Great Mother was washed. This single day was in the second century AD expanded to several days when games were held in honor of Cybele, the Great Mother, a goddess represented by a large stone brought to Rome in 204 BC by instruction of the Oracle of Delphi. Transported all the way from Pessinus in Asia Minor, its arrival must have seen auspicious as it coincided with Rome\'s final victory over Hannibal. ',
    'the second day of the Ludi Megalenses. Originally celebrated on March 27 when the statue of the Great Mother was washed. This single day was in the second century AD expanded to several days when games were held in honor of Cybele, the Great Mother, a goddess represented by a large stone brought to Rome in 204 BC by instruction of the Oracle of Delphi. Transported all the way from Pessinus in Asia Minor, its arrival must have seen auspicious as it coincided with Rome\'s final victory over Hannibal. ',
    'the third day of the Ludi Megalenses. Originally celebrated on March 27 when the statue of the Great Mother was washed. This single day was in the second century AD expanded to several days when games were held in honor of Cybele, the Great Mother, a goddess represented by a large stone brought to Rome in 204 BC by instruction of the Oracle of Delphi. Transported all the way from Pessinus in Asia Minor, its arrival must have seen auspicious as it coincided with Rome\'s final victory over Hannibal. ',
    'the fourth day of the Ludi Megalenses. Originally celebrated on March 27 when the statue of the Great Mother was washed. This single day was in the second century AD expanded to several days when games were held in honor of Cybele, the Great Mother, a goddess represented by a large stone brought to Rome in 204 BC by instruction of the Oracle of Delphi. Transported all the way from Pessinus in Asia Minor, its arrival must have seen auspicious as it coincided with Rome\'s final victory over Hannibal. ',
    'the fifth day of the Ludi Megalenses. Originally celebrated on March 27 when the statue of the Great Mother was washed. This single day was in the second century AD expanded to several days when games were held in honor of Cybele, the Great Mother, a goddess represented by a large stone brought to Rome in 204 BC by instruction of the Oracle of Delphi. Transported all the way from Pessinus in Asia Minor, its arrival must have seen auspicious as it coincided with Rome\'s final victory over Hannibal. ',
    'the sixth day of the Ludi Megalenses. Originally celebrated on March 27 when the statue of the Great Mother was washed. This single day was in the second century AD expanded to several days when games were held in honor of Cybele, the Great Mother, a goddess represented by a large stone brought to Rome in 204 BC by instruction of the Oracle of Delphi. Transported all the way from Pessinus in Asia Minor, its arrival must have seen auspicious as it coincided with Rome\'s final victory over Hannibal. ',
    'the seventh and last day of the Ludi Megalenses, and the only day to include horse races. Originally celebrated on March 27 when the statue of the Great Mother was washed. This single day was in the second century AD expanded to several days when games were held in honor of Cybele, the Great Mother, a goddess represented by a large stone brought to Rome in 204 BC by instruction of the Oracle of Delphi. Transported all the way from Pessinus in Asia Minor, its arrival must have seen auspicious as it coincided with Rome\'s final victory over Hannibal. ',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'Fordicidia, a fertility festival for animal husbandry and farming. Traditionally involving the sacrifice of a pregnant cow to Tellus, the god of the Earth to bring fertility to animals, this deity is best propitiated now by putting out food for the stray kittens of springtime or donating food to a local anmial shelter.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'Cerealia, a festival in honor of Ceres, the goddess of grain. The original festival involved setting loose foxes with tails on fire in the night. Some classicists theorize that this was meant to bring light and warmth to the fields, and burn away disease. Less bloodthirsty celebrations involved women dressed in white running through the city, bearing torches to represent Ceres searching for her daughter Proserpine, who had been kidnapped and married by Saturn. Usher in spring with some ghostly hide and seek.',
    'not a holiday',
    'Parilia, a rustic festival in honor of Pales, a deity of shepherds, flocks and livestock. Pales occurs as both male and female, and sometimes as a pair of gods.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'Robigalia, a ritual to protect crops from disease. Don\'t let your houseplants get mites or rot! The name comes from that of the spirit or numen Robigo, or Robigus, the spirit of the disease who needed to be propitiated. Instead of the traditional sacrifice of a dog, offer a canine friend an extra treat.',
    'not a holiday',
    'not a holiday',
    'the first day of the Ludi Floriales. This was a holiday in honor of Flora, goddess of flowers. It was a fertility festival known for its licentious nature and was important to vine growers. Celebrations featured tables heaped with flowers, and a strip-tease performance by prostitutes. This holiday was later replaced by Maypole celebrations.',
    'the second day of the Ludi Floriales. This was a holiday in honor of Flora, goddess of flowers. It was a fertility festival known for its licentious nature and was important to vine growers. Celebrations featured tables heaped with flowers, and a strip-tease performance by prostitutes. This holiday was later replaced by Maypole celebrations.',
    'the third day of the Ludi Floriales. This was a holiday in honor of Flora, goddess of flowers. It was a fertility festival known for its licentious nature and was important to vine growers. Celebrations featured tables heaped with flowers, and a strip-tease performance by prostitutes. This holiday was later replaced by Maypole celebrations.'
  ],
  ['the fourth day of the Ludi Floriales. This was a holiday in honor of Flora, goddess of flowers. It was a fertility festival known for its licentious nature and was important to vine growers. Celebrations featured tables heaped with flowers, and a strip-tease performance by prostitutes. This holiday was later replaced by Maypole celebrations.',
    'the fifth day of the Ludi Floriales. This was a holiday in honor of Flora, goddess of flowers. It was a fertility festival known for its licentious nature and was important to vine growers. Celebrations featured tables heaped with flowers, and a strip-tease performance by prostitutes. This holiday was later replaced by Maypole celebrations.',
    'the sixth and final day of the Ludi Floriales (and the only day featuring horse races.) This was a holiday in honor of Flora, goddess of flowers. It was a fertility festival known for its licentious nature and was important to vine growers. Celebrations featured tables heaped with flowers, and a strip-tease performance by prostitutes. This holiday was later replaced by Maypole celebrations.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'the first day of the feast of Lemuralia, or Lemuria',
    'not a holiday',
    'the second day of the feast of Lemuralia, or Lemuria',
    'not a holiday',
    'the third day of the feast of Lemuralia, or Lemuria',
    'the anniversary of the Temple of Mars Invictus (Mars the Unconquered)',
    'the Ides: the Mercuralia, in honor of Mercury; Feriae of Jove',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'one of four Agonalia, probably a third festival for Vediovis, a god either so primeval or so obscure that even in the Late Republic period little about him was known. Or perhaps the god was adopted from Bovillae when Rome conquered it and thus not of much interest to Romans, save those who like the Julii hailed from there. This festival seems to have been about protection, or perhaps war. A ram was the usual sacrifice victim and the sacrifice had to be performed by the highest religious official. Probably originally held on the Quirinal Hill.',
    'not a holiday',
    'the second Tubilustrium; Feriae for Vulcan, god of the forge and maker of the sacred trumpets. The trumpets would be ceremonially polished. In the Hall of the Shoemakers a female lamb was sacrificed and Salii, the twelve youths who were leaping priests of Mars, danced through the streets.',
    'QRCF, following Tubilustrium as in March',
    'the anniversary of the Temple of Fortuna Primegenia',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday'
    ],
  ['Kalends: anniversaries of the Temple of Juno Moneta; of the Temple of Mars on the clivus (slope, street) outside the Porta Capena; and possibly of the Temple of the Tempestates (storm goddesses); also a festival of the complex goddess Cardea or Carna',
    'not a holiday',
    'anniversary of the Temple of Bellona',
    'anniversary of the restoration of the Temple of Hercules Custos',
    'anniversary of the Temple of Dius Fidius',
    'not a holiday',
    'Ludi Piscatorii, \"Fishermen\'s Games\", and the first day of Vestalia, in honor of Vesta, goddess of the hearth and home. The Vestals would bake special salted loaves, making this a special holiday for bakers. Fish caught today would be burned at the temple of Vulcan.',
    'anniversary of the Temple of Mens, and the second day of Vestalia, a festival in honor of Vesta, goddess of the hearth and home. The Vestals would bake special salted loaves, making this a special holiday for bakers. ',
    'the third day of Vestalia, a festival in honor of Vesta, goddess of the hearth and home. The Vestals would bake special salted loaves, making this a special holiday for bakers. ',
    'the fourth day of Vestalia, a festival in honor of Vesta, goddess of the hearth and home. The Vestals would bake special salted loaves, making this a special holiday for bakers. ',
    'Matralia in honour of Mater Matuta; also the anniversary of the Temple of Fortuna in the Forum Boarium, and the fifth day of Vestalia, a festival in honor of Vesta, goddess of the hearth and home. The Vestals would bake special salted loaves, making this a special holiday for bakers. ',
    'the sixth day of Vestalia, a festival in honor of Vesta, goddess of the hearth and home. The Vestals would bake special salted loaves, making this a special holiday for bakers. ',
    'the Ides of June - Feriae of Jove and the seventh day of Vestalia, a festival in honor of Vesta, goddess of the hearth and home. The Vestals would bake special salted loaves, making this a special holiday for bakers.',
    'the eighth day of Vestalia, a festival in honor of Vesta, goddess of the hearth and home. The Vestals would bake special salted loaves, making this a special holiday for bakers. ',
    'the ninth and final day of Vestalia, a festival in honor of Vesta, goddess of the hearth and home. The Vestals would bake special salted loaves, making this a special holiday for bakers. ',
    'not a holiday',
    'Matralia - a holiday devoted to Mater Matuta, a virgin goddess devoted to dawn and matrons. Offerings were taken to her temple to ask for blessings upon children and nephews or nieces.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'the Black Day - the Anniversary of Trasimene. It is considered unlucky as being the anniversary of the defeat to Hannibal in 217 BC.',
    'not a holiday',
    'not a holiday',
    'Fors Fortuna, a holiday in honor of Fortuna. Sacrifices were taken to two altars along the Tiber outside of the city.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday'
  ],
  ['not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'Poplifugia - a festival to Jupiter. Like most of the festivals, it probably had its origin in the time of Rome\'s kings. The name means \"Flight of the People\" and probably refers to an event dimly remembered even in Republican times.',
    'the first day of the Ludi Apollinares, or games of Apollo, from July 6th to July 13th. In 212 BC, some years after the defeat to Hannibal at Cannae, a prophecy came to light. This prophecy had two parts, the first, to avoid battle at a place called \"Canna\". Romans were all too ready to identify this with their recent horrendous defeat at Cannae. The second said that to avoid such problems the Romans must have a special festival for Apollo in the Greek fashion. The Sibylline books were consulted to determine the correct rites. In 208 BC there was a biological plague so the Ludi Apollinares were repeated. They proved so popular that they were instituted as a regular event',
    'the second day of the the Ludi Apollinares, or games of Apollo, from July 6th to July 13th. In 212 BC, some years after the defeat to Hannibal at Cannae, a prophecy came to light. This prophecy had two parts, the first, to avoid battle at a place called \"Canna\". Romans were all too ready to identify this with their recent horrendous defeat at Cannae. The second said that to avoid such problems the Romans must have a special festival for Apollo in the Greek fashion. The Sibylline books were consulted to determine the correct rites. In 208 BC there was a biological plague so the Ludi Apollinares were repeated. They proved so popular that they were instituted as a regular event',
    'the third day of the Ludi Apollinares, or games of Apollo, from July 6th to July 13th. In 212 BC, some years after the defeat to Hannibal at Cannae, a prophecy came to light. This prophecy had two parts, the first, to avoid battle at a place called \"Canna\". Romans were all too ready to identify this with their recent horrendous defeat at Cannae. The second said that to avoid such problems the Romans must have a special festival for Apollo in the Greek fashion. The Sibylline books were consulted to determine the correct rites. In 208 BC there was a biological plague so the Ludi Apollinares were repeated. They proved so popular that they were instituted as a regular event',
    'the fourth day of the Ludi Apollinares, or games of Apollo, from July 6th to July 13th. In 212 BC, some years after the defeat to Hannibal at Cannae, a prophecy came to light. This prophecy had two parts, the first, to avoid battle at a place called \"Canna\". Romans were all too ready to identify this with their recent horrendous defeat at Cannae. The second said that to avoid such problems the Romans must have a special festival for Apollo in the Greek fashion. The Sibylline books were consulted to determine the correct rites. In 208 BC there was a biological plague so the Ludi Apollinares were repeated. They proved so popular that they were instituted as a regular event',
    'the fifth day of the Ludi Apollinares, or games of Apollo, from July 6th to July 13th. In 212 BC, some years after the defeat to Hannibal at Cannae, a prophecy came to light. This prophecy had two parts, the first, to avoid battle at a place called \"Canna\". Romans were all too ready to identify this with their recent horrendous defeat at Cannae. The second said that to avoid such problems the Romans must have a special festival for Apollo in the Greek fashion. The Sibylline books were consulted to determine the correct rites. In 208 BC there was a biological plague so the Ludi Apollinares were repeated. They proved so popular that they were instituted as a regular event',
    'the sixth day of the Ludi Apollinares, or games of Apollo, from July 6th to July 13th. In 212 BC, some years after the defeat to Hannibal at Cannae, a prophecy came to light. This prophecy had two parts, the first, to avoid battle at a place called \"Canna\". Romans were all too ready to identify this with their recent horrendous defeat at Cannae. The second said that to avoid such problems the Romans must have a special festival for Apollo in the Greek fashion. The Sibylline books were consulted to determine the correct rites. In 208 BC there was a biological plague so the Ludi Apollinares were repeated. They proved so popular that they were instituted as a regular event',
    'the seventh day of the Ludi Apollinares, or games of Apollo, from July 6th to July 13th. In 212 BC, some years after the defeat to Hannibal at Cannae, a prophecy came to light. This prophecy had two parts, the first, to avoid battle at a place called \"Canna\". Romans were all too ready to identify this with their recent horrendous defeat at Cannae. The second said that to avoid such problems the Romans must have a special festival for Apollo in the Greek fashion. The Sibylline books were consulted to determine the correct rites. In 208 BC there was a biological plague so the Ludi Apollinares were repeated. They proved so popular that they were instituted as a regular event',
    'the eighth day of the Ludi Apollinares, or games of Apollo, from July 6th to July 13th. In 212 BC, some years after the defeat to Hannibal at Cannae, a prophecy came to light. This prophecy had two parts, the first, to avoid battle at a place called \"Canna\". Romans were all too ready to identify this with their recent horrendous defeat at Cannae. The second said that to avoid such problems the Romans must have a special festival for Apollo in the Greek fashion. The Sibylline books were consulted to determine the correct rites. In 208 BC there was a biological plague so the Ludi Apollinares were repeated. They proved so popular that they were instituted as a regular event',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'a Black Day - a day considered unlucky since it was the anniversary of the near extinction of the Fabius clan at Cremera in 477 BC and defeat by the Gauls at Allia in 390 BC which led to the later sacking of Rome itself.',
    'the first day of Lucaria, observed on the 19th and 21st. Commemorates the day of defeat of the Roman army by the Gauls in 390 BC. Romans hid in the woods (lucus) and legendarily returned to defeat the Gauls on their way back home. The festival was celebrated in a large grove, said to be where the Romans had hidden, between the Tiber and the Salarian Way.',
    'the first day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races.',
    'the second day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races. Also the second day of Lucaria, observed on the 19th and 21st. Commemorates the day of defeat of the Roman army by the Gauls in 390 BC. Romans hid in the woods (lucus) and legendarily returned to defeat the Gauls on their way back home. The festival was celebrated in a large grove, said to be where the Romans had hidden, between the Tiber and the Salarian Way.',
    'the third day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races.',
    'Neptunalia - a holiday dedicated to Neptune. The men who worked on the barges and docks of the Tiber River celebrated. In the heat of the summer Romans they would build huts out of branches and leaves and inside eat, drink and amuse themselves. It seems there were also games held. This was also a day on which citizen committees could vote on civil or criminal issues. Also the fourth day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races.',
    'the fifth day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races.',
    'Furrinalia - a holiday dedicated to o Furrina. Furrina had a priestess dedicated to her and a sacred grove where the festival may have been celebrated. This very early goddess was associated with water and this may have been a festival meant to ensure there was no drought in the heat of the summer. Also, the sixth day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races.',
    'the seventh day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races.',
    'the eight day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races.',
    'the ninth day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races.',
    'the tenth day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races.',
    'the eleventh day of the Ludi Victoriae Caesarae - games established in 46 BC by Julius Caesar to celebrate his Roman Civil War victory over Pompeius at Pharsalus. The last four (of eleven) days featured chariot races.',
    'not a holiday'
  ],
  ['not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'Portunus, a holiday dedicated to Portunus, originally the god of keys, doors and livestock, who because his name sounded like the words for gate and harbor became a god of these things. Celebrations included solemnly throwing keys into a fire for good luck. Probably there were also sacrifices at his temple in the Forum Boarium.',
    'not a holiday',
    'not a holiday',
    'the second holiday of Vinalia (the first being in April). This was dedicated to Jupiter and Venus. This was known as the the Vinalia rustica. In April there was another Vinalia, known as Vinalia prima (first) or Vinalia urbana (urban). Important for vine growers, corresponding to the times of harvest and crushing of grapes. This day was also a holiday for gardeners. Kitchen- and market-gardens were dedicated to Venus. A female lamb was sacrificed to Jupiter by his priest.',
    'not a holiday',
    'Consualia, dedicated to Consus, god responsible for protection of the harvest. His temple was underground similar to a grain storage vault. This is one of two festivals to this god. The underground stored grains were uncovered on this day, probably to be blessed. Donkeys and mules were adorned with flowers and paraded through the streets, not being allowed to do their normal work. Chariot races were also held. In Roman history this was said to be the day on which Romulus abducted the Sabine women',
    'not a holiday',
    'Volcanalia, a holiday dedicated to Vulcan, god of life-sustaining fire. This was celebrated to avoid fire burning the almost ripe crops. Curiously, bonfires were made and live fish or small animals were thrown in to be consumed instead of humans. People would also hang out their clothes and fabrics under the sun and start the day working by a candle to demonstrate a beneficial use of fire. Later in the empire, a red bull calf and a red boar were sacrificed to a new altar to Vulcan on the Quirinal Hill.',
    'not a holiday',
    'Opiconsivia, a holiday dedicated to Ops Consiva, goddess of the earth, agricultural resources and wealth, and also wife of Saturn. Vestal Virgins held rites to give thanks for the fertility of the earth and the flamines or priestesses of Quirinus also participated. The main priestess wore a white veil, horses and mules wore chaplets of flowers and there was a chariot race in the Circus Maximus',
    'not a holiday',
    'Volturnalia, a holiday dedicated to Volturnus, god of the Tiber River. Celebrations included feasting, wine and games.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday'
  ],
  [ 'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'the first day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the second day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the third day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the fourth day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the fifth day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the sixth day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the seventh day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the eighth day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the ninth day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the tenth day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the eleventh day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the twelfth day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the thirteenth day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the fourteenth day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'the fifteenth day of the Ludi Romani. Originally the games would happen when a general, desperate for victory, would pledge a festival to the gods if he were given victory. Eventually they were so popular that they became an annual event. The games were later extended by one day by Marcus Antonius in honor of the deceased Julius Caesar.',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday',
    'not a holiday'
  ],
  [   'not a holiday',
      'not a holiday',
      'the first day of the Ludi Augustales, in honor of Augustus.',
      'the second day of the Ludi Augustales, in honor of Augustus.',
      'the third day of the Ludi Augustales, in honor of Augustus.',
      'the Anniversary of Arausio - a black day, considered unlucky due to defeat at the hands of Germans tribes in 1-5 BC. Also the fourth day of the Ludi Augustales, in honor of Augustus.',
      'the fifth day of the Ludi Augustales, in honor of Augustus',
      'the sixth day of the Ludi Augustales, in honor of Augustus.',
      'the seventh day of the Ludi Augustales, in honor of Augustus.',
      'the eighth day of the Ludi Augustales, in honor of Augustus',
      'Meditrinalia - a holiday to Jupiter, in his form as the wine-god, and Meditrina, goddess of healing and medicine. This was the first occasion on which Romans tasted the year\'s new vintage. Also the ninth day of the Ludi Augustales, in honor of Augustus.',
      'the tenth day of the Ludi Augustales, in honor of Augustus.',
      'Fontinalia - a holiday in honor of Fons or Fontus, god of fountains, wells and springs. Fountains and wellheads around Rome were decorated with garlands.',
      'not a holiday',
      'Equus October - a race of two-horse chariots on the Campius Martius in honor of Mars. The right hand horse was sacrificed to the god with the tail being taken to the regia where its blood was left to drip on the hearth. The head was fought over between the residents of the Via Sacra (the rich and powerful) and the Subura (the poor). This festival and the next represented the usual close of the military season.',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'Armilustrium - a holiday dedicated to Mars. This marked the end of the military campaigning season. Soldiers\' weapons were ritually purified and stored for the winter on the Aventine Hill. The assembled army was garlanded with flowers and reviewed in the Circus Maximus. Trumpets were played. There was a procession with torches and sacrificial animals.',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'the first day of the Ludi Victoriae Sulli, games instituted to commemorate the victory of Sulla over the Marian faction, saving Rome.',
      'the second day of the Ludi Victoriae Sulli, games instituted to commemorate the victory of Sulla over the Marian faction, saving Rome.',
      'the third day of the Ludi Victoriae Sulli, games instituted to commemorate the victory of Sulla over the Marian faction, saving Rome.',
      'the fourth day of the Ludi Victoriae Sulli, games instituted to commemorate the victory of Sulla over the Marian faction, saving Rome.',
      'the fifth day of the Ludi Victoriae Sulli, games instituted to commemorate the victory of Sulla over the Marian faction, saving Rome.',
      'the sixth day of the Ludi Victoriae Sulli, games instituted to commemorate the victory of Sulla over the Marian faction, saving Rome.'
    ],
    ['the seventh and last day of the Ludi Victoriae Sulli, games instituted to commemorate the victory of Sulla over the Marian faction, saving Rome.',
      'not a holiday',
      'not a holiday',
      'the first day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the second day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the third day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the fourth day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the fifth day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the sixth day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the seventh day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the eighth day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the ninth day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the tenth day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the eleventh day (and the first of the final four days) of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the twelfth day (and the second of the final four days) of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the thirteenth day (and the third of the final four days) of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'the fourteenth (and last) day of the Ludi Plebeian - the second biggest holiday of games for the people. One day was given over to the Epulum Iovis and one to the Transvectio Equitum, the parade of the Equites. The last four days were given up to horse races.',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday'
    ],
    ['not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'Agonalia - the other day sacred to Janus, the bookend to that of January 9. Later also a day sacred to Sol Indiges. This was a festival originally for the protection of the king. A ram was the usual sacrifice victim. Probably originally held on the Quirinal Hill.',
      'not a holiday',
      'not a holiday',
      'not a holiday',
      'Consualia - a day sacred to Consus, god of Time, whose presence is obviously connected with the end of the year. This is the start of the Halcyon Days, the seven days preceding and the seven days following the Winter Solstice. This is one of two festivals to this god. The underground stored grains were uncovered on this day, probably to be blessed. Donkeys and mules were adorned with flowers and paraded through the streets, not being allowed to do their normal work. Chariot races were also held. In Roman history this was said to be the day on which Romulus abducted the Sabine women.',
      'the second day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'Saturnalia - celebrated in honor of Saturn, and the greatest of the Roman annual holidays. Saturnalia was originally one day long but grew until it eventually became a five-day holiday, celebrated over the course of seven days. It began with cries of "Io Saturnalia!" and the sacrifice of young pigs. It was a holiday where anyone could become King of Saturnalia - even a slave - by the roll of the dice, and was marked by drinking and feasting. It was traditional to deck the halls with boughs of laurel and green trees as well as a number of candles and lamps to dispel the darkness. People exchanged traditional gifts of small dolls. Gifts could also include food items such as pickled fish, sausages, beans, olives, figs, prunes, nuts and cheap wine ',
      'the fourth day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'the fifth day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'the sixth day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'the seventh day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'the winter solstice, and the central day of the Halcyon days.',
      'the ninth day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'the tenth day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'the eleventh day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'the twelfth day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'the thirteenth day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'the fourteenth day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'the fifteenth and last day of the Halcyon days - seven days preceding and seven days following the winter solstice.',
      'not a holiday',
      'not a holiday'
    ]
  ];
